### ISSUE TITLE
Las tropas se teletrasportan a territorios aleatorios cuando mueves 69 tropas

### ISSUE THREAD

**Issue by pkmniako** [UNIZAR-30226-2021-01/Prueba#2]
Las tropas se teletrasportan a territorios aleatorios cuando mueves 69 tropas

**Comment by CursedR3N** [comment]
No worries, estamos con ello, tenemos al development team (@alecron solo ) trabajando en ello

**Comment by alecron** [comment]
`
<h1>not funny<h1>
`

**Comment by Daboposki** [comment]
didnt laugh

**Comment by CursedR3N** [comment]
Como se ha mencionado en #4, se ha solucionado este error en e5b1a0a
