### ISSUE TITLE
Bug encontrado: Formato americano

### ISSUE THREAD

**Issue by CursedR3N** [UNIZAR-30226-2021-01/Prueba#3]
No se porque pero cuando pones la fecha te sale el mes despues del día????
Esto esta obviamente mal, como se cambia?
# NO FUNCIONA
Ah ya que estais id arreglar el bug #2 que es más importante que este

**Comment by pkmniako** [comment]
Propongo un patrón de clases para poder implementar distintos formatos de fechas

**Comment by pkmniako** [comment]
Added `fecha.cpp`, might want to check it's functionality
