### ISSUE TITLE
Donde esta Samu

### ISSUE THREAD

**Issue by pkmniako** [UNIZAR-30226-2021-01/Prueba#5]
Pero donde esta

**Comment by Daboposki** [comment]
mecmec

**Comment by CursedR3N** [comment]
Asigno a @Daboposki como responsable de encontrar a Samuel

**Comment by Daboposki** [comment]
rechazo

**Comment by alecron** [comment]
### OOF

**Comment by Daboposki** [comment]
asigno a @samulix20

**Comment by CursedR3N** [comment]
> rechazo

No puedes

**Comment by pkmniako** [comment]
Como @Daboposki rechaza, asigno a @CursedR3N

**Comment by CursedR3N** [comment]
> Como @Daboposki rechaza, asigno a @CursedR3N

No puedes

**Comment by CursedR3N** [comment]
# Situación actual
- [ ] Samuel encontrado
- [x] Samuel escondido

**Comment by pkmniako** [comment]
He contratado a un serie de mercenarios para encontrar y capturar a Samuel.
